### ISSUE TITLE
junit parallel execution yaml file doesn't work

### ISSUE THREAD

**Issue by YeonCheolGit** [junit-team/junit5#3003]
_(Maybe this is silly question)_

I've already searched google a lot but couldn't find answer for this.

I am trying to execute junit test parallelly. 
Fortunately `.properties` file works.
But `.yml` file doesn't work for this.

Is there any way to configure this in yaml?

- Spring boot 2.7.2
- Gradle 7.5
- Junit5

`Test class`
```
@TestPropertySource(locations = ["classpath:junit-platform.yml"])
```

`.properties`
```
junit.jupiter.execution.parallel.enabled=true
junit.jupiter.execution.parallel.mode.classes.default=concurrent
junit.jupiter.execution.parallel.mode.default=same_thread
junit.jupiter.execution.parallel.config.strategy=dynamic
junit.jupiter.execution.parallel.config.dynamic.factor=1
```

`.yml`
```
junit:
  jupiter:
    execution:
      parallel:
        enabled: true
        config:
          strategy: dynamic
          dynamic:
            factor: 1
        mode:
          classes:
            default: concurrent
          default: same_thread
```
